global:
    recoil_on_switch: true
    debug: true
recoil_profiles:
    - name: "Single"
      automatic: false
      pulse_length: 40
      delay_between_pulses: 0
      offscreen: false
      strength: 5
    - name: "Single_Strong"
      automatic: false
      pulse_length: 80
      delay_between_pulses: 0
      offscreen: false
      strength: 10
    - name: "Auto_Fast"
      automatic: true
      pulse_length: 40
      delay_between_pulses: 3
      offscreen: false
      strength: 1
    - name: "Auto_Default"
      automatic: true
      pulse_length: 50
      delay_between_pulses: 9
      offscreen: false
      strength: 1
    - name: "Auto_Strong"
      automatic: true
      pulse_length: 60
      delay_between_pulses: 13
      offscreen: false
      strength: 1
game_profiles:
    - name: "House of the Dead 4"
      profile: "Auto_Fast"
      offscreen_reload: false
      input_type: "joystick"
      match:
        exe: "BudgieLoader.exe"
        title: "TeknoBudgie - House of the Dead 4"
    - name: "Farcry Paradise Lost"
      profile: "Auto_Strong"
      match:
        exe: "FarCry_r.exe"
    - name: "Sinden"
      profile: "Single"
      input_type: "mouse"
      match:
        title: "SindenLightgun"
    - name: "House of the Dead: Scarlet Dawn"
      profile: "Single"
      match:
        exe: "Hodzero-Win64-Shipping.exe"
      memscan:
        paths:
          - Hodzero-Win64-Shipping.exe+0329C400,0x30,0xE10,0x134 # Player 1
          - Hodzero-Win64-Shipping.exe+0329C400,0x30,0xE10,0x634 # Player 2
        type: byte
        match:
          0x0: "Auto_Fast" # machine gun
          0x15: "Single_Strong" # shotgun
          0x16: "Single" # MGM 700
          0x12: "Auto_Fast" # machine gun ex
          0x13: "Auto_Fast" # gatling gun
          0x9: "Single" # laser
          0x18: "Single" # heat ray
          0x7: "Single" # Hand Grenade
          0x5: "Single" # Grenade Launcher
          0x3: "Single" # incendiary gun
          0xB: "Single" # rocket launcher
          0x19: "Single" # energy cannon
          0x1A: "Single" # SW cannon
          0x1C: "Single" # shield
    - name: "Dead Containment Demo"
      profile: "Single"
      match:
        exe: "DeadContainment-Win64-Shipping.exe"
      memscan:
        paths:
          - DeadContainment-Win64-Shipping.exe+04AAF978,0x0,0x110,0x2F0,0x2E8
        type: byte
        match:
          0x0: "Single" # Not sure
          0x1: "Single" # Single fire
          0x2: "Auto_Fast" # Auto fire
    - name: "Assault Cube"
      profile: "Single"
      match:
        exe: "ac_client.exe"
      memscan:
        paths: 
          - ac_client.exe+0x0018AC00,0x364,0x4
        type: byte
        match: 
          0x0: "Single" # Knife
          0x1: "Single" # Glock
          0x6: "Auto_Fast" # AR
          0x7: "Single" # Sniper
    - name: "Ghost Squad"
      profile: "Single"
      match:
        exe: "Dolphin.exe"
        title: "Ghost Squad"
      memscan:
        paths:
         - "0x80507308,0xa5f" #main weapon? 0xa83 is subweapon? other offsets: 80507360 + 95f, 805073b8 + 91f, 80507410 + 5f, 806d3e64 + a5f 
        type: dolphinbyte
        match:
          0x1: "Single" # Single
          0x2: "Single" # Gun Burst-2
          0x3: "Auto_Fast" # Burst-3
          0x4: "Auto_Fast" # Auto
          0x5: "Single" # Grenade
          0x0: "Single" # Dead?