name: SindenCompanion Build

on: 
  push: 
    branches: master

jobs: 
  build: 
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
  
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - uses: nuget/setup-nuget@v1
  
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Download Sinden Drivers
      run: |
        Invoke-WebRequest https://www.sindenlightgun.com/software/SindenLightgunWindowsSoftwareV2.05beta.zip -OutFile sinden.zip
        Expand-Archive .\sinden.zip -DestinationPath .\sinden
        cp .\sinden\LightgunBeta2.05\Lightgun.exe

    - name: Restore Packages
      run: nuget restore SindenCompanion.sln

    - name: Build Solution
      run: |
        msbuild.exe SindenCompanion.sln /nologo /nr:false /p:platform="x64" /p:configuration="Release" /p:PublishUrl="../_build"

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/SindenCompanion.exe,build/SindenHook.dll,build/config.yaml"
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: ${{ steps.tag_version.outputs.changelog }}